### ISSUE TITLE
CODRA docker run error

### ISSUE THREAD

**Issue by rudra0713** [NLPbox/codra-docker#5]
Hi,
 I am facing an error while trying to run the code: docker run codra . The error is :
`mv: cannot stat '/opt/codra-rst-parser/tmp_doc.dis': No such file or directory
cat: input_long.txt.dis: No such file or directory
`
Any help will be highly appreciated.

**Comment by arne-cl** [comment]
Dear @rudra0713,

sorry for the late reply. I can't reproduce your error on my machine. Can you try to run it manually inside the container?

```
$ docker build --no-cache -t codra .
$ docker run --entrypoint=/bin/bash -ti codra
root@ca9be89c5d1f:/opt/codra-rst-parser# ./codra.sh input_short.txt 
( Root (span 1 2)
  ( Satellite (leaf 1) (rel2par Contrast) (text _!Although they did n't like it ,_!) )
  ( Nucleus (leaf 2) (rel2par span) (text _!they accepted the offer ._!) )
)
```

**Comment by wengcindy** [comment]
Hi, I'm having the same issue. I ran the command above and got the same error: 
```
root@fee7c2d0c286:/opt/codra-rst-parser# ./codra.sh input_short.txt 
Traceback (most recent call last):
  File "Discourse_Parser.py", line 686, in <module>
    do_parse(sys.argv[1])
  File "Discourse_Parser.py", line 678, in do_parse
    apply_sent_model("tmp_sen.feat", java_classpath, java_prog)
  File "Discourse_Parser.py", line 654, in apply_sent_model
    subprocess.check_call(['java', '-classpath', java_classpath, java_prog, '--testing', test_f, '--model-file', 'dcrf.sen.gz'], stdout=F_W, stderr=F_W2)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-classpath', 'Tools/grmm/class:Tools/grmm/lib/mallet-deps.jar:Tools/grmm/lib/grmm-deps.jar', 'edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty', '--testing', 'tmp_sen.feat', '--model-file', 'dcrf.sen.gz']' returned non-zero exit status 1
mv: cannot stat '/opt/codra-rst-parser/tmp_doc.dis': No such file or directory
cat: input_short.txt.dis: No such file or directory
```

**Comment by ccolonna** [comment]
Hi, same problem here: got the same output from that.

`linux@Linux:~/Progetti/rst-tool/codra-docker$ ls
codra.sh    input_long.txt   output_long.dis   README.md
Dockerfile  input_short.txt  output_short.dis  test_codra.py


linux@Linux:~/Progetti/rst-tool/codra-docker$  docker run --entrypoint=/bin/bash -ti codra

root@7e5331494db2:/opt/codra-rst-parser# ls
Chain.pm                Tools             input_short.txt  template.crf
ContFeatures.py         TopicFeatures.py  lexChain.pl      template.ugm
Discourse_Parser.py     Word.pm           model.seg        test_codra.py
Discourse_Segmenter.py  codra.sh          ngrams           tmp_doc.prob
LICENSE-2.0.txt         dcrf.doc.gz       parse_doc.rel    train.seg
Parse.py                dcrf.sen.gz       parse_sen.rel
SynFeatures.py          dependencies      readme
TAG_SETS                input_long.txt    serialize.py


root@7e5331494db2:/opt/codra-rst-parser# ./codra.sh input_short.txt 

Traceback (most recent call last):
  File "Discourse_Parser.py", line 686, in <module>
    do_parse(sys.argv[1])
  File "Discourse_Parser.py", line 678, in do_parse
    apply_sent_model("tmp_sen.feat", java_classpath, java_prog)
  File "Discourse_Parser.py", line 654, in apply_sent_model
    subprocess.check_call(['java', '-classpath', java_classpath, java_prog, '--testing', test_f, '--model-file', 'dcrf.sen.gz'], stdout=F_W, stderr=F_W2)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-classpath', 'Tools/grmm/class:Tools/grmm/lib/mallet-deps.jar:Tools/grmm/lib/grmm-deps.jar', 'edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty', '--testing', 'tmp_sen.feat', '--model-file', 'dcrf.sen.gz']' returned non-zero exit status 1
mv: cannot stat '/opt/codra-rst-parser/tmp_doc.dis': No such file or directory
cat: input_short.txt.dis: No such file or directory
`

**Comment by ghost** [comment]
Me too. It was working but with a new build, I got this error. 

```
Traceback (most recent call last):
  File "Discourse_Parser.py", line 686, in <module>
    do_parse(sys.argv[1])
  File "Discourse_Parser.py", line 678, in do_parse
    apply_sent_model("tmp_sen.feat", java_classpath, java_prog)
  File "Discourse_Parser.py", line 654, in apply_sent_model
    subprocess.check_call(['java', '-classpath', java_classpath, java_prog, '--testing', test_f, '--model-file', 'dcrf.sen.gz'], stdout=F_W, stderr=F_W2)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-classpath', 'Tools/grmm/class:Tools/grmm/lib/mallet-deps.jar:Tools/grmm/lib/grmm-deps.jar', 'edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty', '--testing', 'tmp_sen.feat', '--model-file', 'dcrf.sen.gz']' returned non-zero exit status 1
mv: cannot stat '/opt/codra-rst-parser/tmp_doc.dis': No such file or directory
cat: input_long.txt.dis: No such file or directory
```

**Comment by ghost** [comment]
any update on this issue?

**Comment by arne-cl** [comment]
Dear @moh55m55,

I remember that I had the same issue on Ubuntu 16.04 at some point, but I can no longer reproduce it on that OS, so I assume that there is some interaction between the Linux kernel version used and the Java runtime that is running in the container.

I installed Ubuntu 14.04 on a spare laptop and there I could indeed reproduce the problem.
I tried to rebuild the mallet/grmm stuff that the Java runtime crashes on, but that didn't help.

Next, I tried to run the `java -classpath Tools/grmm/class:Tools/grmm/lib/mallet-deps.jar:Tools/grmm/lib/grmm-deps.jar edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty --testing tmp_sen.feat --model-file dcrf.sen.gz ` in a debugger, where I found that the crash occurs when the model file `dcrf.sen.gz` is loaded.

After unpacking the file, I noticed that `dcrf.sen` is of type `Java serialization data, version 5`.
My next guess would be to try to rebuild that file, but I don't know when I will have time for that.

Which OS and Docker version are you using?

**Comment by pampillo** [comment]
Hi, having the same issue, I have Mac OSX Catalina 10.15 and java version "13.0.1" on the host. I have been running the codra docker as I have a prebuilt VM with the installation of a parser, but both installations have the same issues. as shown below:
`Exception in thread "main" java.lang.IllegalStateException: unread block data
	at java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:2840)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1660)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2344)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:595)
	at edu.umass.cs.mallet.grmm.learning.ACRF.readObject(ACRF.java:1748)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2235)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2126)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1625)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:465)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:423)
	at edu.umass.cs.mallet.base.util.FileUtils.readGzippedObject(FileUtils.java:163)
	at edu.umass.cs.mallet.base.util.FileUtils.readObject(FileUtils.java:62)
	at edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty.main(AcrfForTestJoty.java:48)
`

**Comment by lmvasque** [comment]
Hi @arne-cl,

Thanks for your interesting work. I'm looking forward for using this parser, but I'm getting the same issues reported above (both using the codra-docker and the codra-service). Did you manage to update the code? Here are the details from my side.

Reported incident:
```
subprocess.CalledProcessError: Command '['java', '-classpath', 'Tools/grmm/class:Tools/grmm/lib/mallet-deps.jar:Tools/grmm/lib/grmm-deps.jar', 'edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty', '--testing', 'tmp_sen.feat', '--model-file', 'dcrf.sen.gz']' returned non-zero exit status 1
mv: cannot stat '/opt/codra-rst-parser/tmp_doc.dis': No such file or directory
```

Running the failing java command manually:
```
$ java -classpath Tools/grmm/class:Tools/grmm/lib/mallet-deps.jar:Tools/grmm/lib/grmm-deps.jar edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty --testing tmp_sen.feat --model-file dcrf.sen.gz 
Error: Could not find or load main class edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty
Caused by: java.lang.ClassNotFoundException: edu.umass.cs.mallet.grmm.learning.AcrfForTestJoty
```
Files on my directory:
```
Dockerfile
README.md
codra_hug_api.py
input_long.txt
input_short.txt
test_api.py
```

Maybe we are just missing some files or should I assume they are in the Docker file? I also did tried to download: dcrf.sen.gz
https://sourceforge.net/p/codra-rst-parser/code/ci/master/tree/dcrf.sen.gz

But it says: _Sorry, the permissions for this page don't allow you to access it. File too large to download._

I'm running with the following specs:
OS: MacOS 11.5.2 (BigSur)
Docker version 20.10.10, build b485636

I'll appreciate any additional advice. Thanks for your support!

Best,

Laura

**Comment by arne-cl** [comment]
Dear @lmvasque,

thank you for your detailed bug report. I haven't worked on this recently, but I'll try if I can make it work on MacOS using Vagrant (instead of Docker) [1] before I finally digging deeper into the Java serialization issue mentioned above [2].

Best,
Arne

[1] https://stackoverflow.com/questions/66261101/using-vagrant-on-github-actions-ideally-incl-virtualbox
[2] https://github.com/NLPbox/codra-docker/issues/5#issuecomment-606842910

**Comment by lmvasque** [comment]
Dear @arne-cl,

Thanks for your prompt response! Sure, we can give that a try. Let me know and I can run the required steps to see how it goes.

Best,

Laura

**Comment by lmvasque** [comment]
Dear @arne-cl,

I have a question regarding the format of the codra parser, is this a custom format or is this something you can find in other parsers too? 

```
( Root (span 1 22)
  ( Nucleus (leaf 1) (rel2par TextualOrganization) (text _!Status update on the Chris Stevens mission to Benghazi :_!) )
  ( Nucleus (span 2 22) (rel2par TextualOrganization)
    ( Nucleus (span 2 8) (rel2par span)
```

I'm considering my options in case we cannot make it work as you mentioned. I'm currently replicating another work that uses these trees as an input. Suggestions and alternatives are welcome!

Best,

Laura

**Comment by arne-cl** [comment]
Dear Laura,

you can test six different parsers on my [RST demo website](https://rst-workbench.arne.cl/).
The underlying [rst-converter-service](https://github.com/rst-workbench/rst-converter-service) library reads
many RST formats, but so far only writes .dis and .rs3.

However, the "CODRA format" is almost identical to .dis (there are some differences in escaping if I remember correctly),
so you could just use any of the other parsers from the rst-workbench, convert the output to .dis
and try that with your pipeline. If the output format needs tweaking, please let me know.

Best,
Arne

**Comment by arushirai1** [comment]
Thank you so much for building this tool. I'm having the same issue as this thread on three different OS/distro: MacOS, Debian, CentOS. Is there any fix for this or recommendation on what OS to use?

**Comment by arne-cl** [comment]
Dear @arushirai1,

sorry for the late reply. I had no idea this error on any linux later than Ubuntu 14.04.
I've been using this Dockerfile successfully on Ubuntu 16.06, 18.04 and 20.04 (as well as Linux Mint,
but that should be binary compatible to Ubuntu).

Which version of Debian did you use?
